# -*- coding: utf-8 -*-

# list of random replies

replies_dict = {
    'kommunist': ['Verdammte Kommunisten',
                  'Wer hat uns verraten?',
                  'Das ist nun doch zu einfach!',
                  'das konzept ist eigentlich gut, nur die Umsetzungen...'],
    'ak-47': ['Kommunisten-Waffe',
              u'zuverlässige Waffe!'],
    'usa': [u'bestes Land überhaupt',
              u'USA? die spionieren uns aus!'],
    'kalaschnikow': ['Kommunisten-Waffe',
                     u'zuverlässige Waffe!'],
    'schorle': ['einer geht noch',
                'mit 3 Eis!',
                'ich trink den lieber pur'],
    'gesellschaft': ['gesellschaft ist eh kaputt',
                     'meine Steuern!'],
    'teilen': ['wer teilt verliert',
               'jeder sollte was abgeben, wenn er genug hat'],
    'waffe': ['mehr davon',
              'jeder sollte eine haben',
              'sind zurecht verboten'],
    'nra': ['eine wichtige, gesellschaftsbildende Institution',
            'ziemlich konservativer laden'],
    'kollege': ['die besten. also deine.',
                'manchmal sind sie schon komisch'],
    'firma': ['gibt nur eine',
              '@aexea'],
    'suite': ['Prost!',
              'schon wieder?'],
    '212': ['Prost!',
            'schon wieder?'],
    'minibar': ['Prost!',
                'schon wieder?'],
    'schnitzel': ['urdeutsches gericht',
                  'gibts das heute mal in vegetarisch?'],
    'damals': ['damals... als startup!',
               'damals war eh alles besser',
               'naja, heute ist es eigentlich schon cool.'],
    'krieg': ['eigentlich haben wir den gar nicht so verloren',
              u'läuft!'],
    'freund': ['freunde sollte man haben'],
    'nerd': ['davon haben wir echt einige mittlerweile',
             'coole jungs',
             'die Moons!'],
    'bier': ['noch nen schorle dazu?',
             'lieber nen schorle'],
    'clinton': ['one miller lite please!'],
    'beer': ['one miller lite please!'],
    'vfb': ['hoffentlich steigen wir dann bald wieder auf',
            u'müsste man mal abwickeln und neumachen'],
    'neulich': ['neulich war nach damals'],
    'spassfest': ['mit parade truck!',
                  u'nen original oktoberfestbesuche müsste man auch wieder mal machen'],
    'germantown': ['mit parade truck!',
                   u'nen original oktoberfestbesuche müsste man auch wieder mal machen'],
}

nothing_found = ['ich weis gar nicht, was ich dazu sagen soll.',
                 u'mir gehen die texte aus',
                 u'unfassbar',
                 u'ich bin sprachlos',
                 u'Jo!',
                 u'Yo!',
                 u'Prost?',
                 u'Alter!',
                 ]
